# -*- coding: utf-8 -*-
"""tensorflow

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YIvAyHvlZx1Al6xhnpk5QcRJU-0HXj6n
"""
# 张量运算
import tensorflow as tf
print(tf.__version__)
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
print(a+b)
sess = tf.Session()
print(sess.run(a+b))
print(a.graph is tf.get_default_graph())


# 计算图
g1 = tf.Graph()
with g1.as_default():
    a = tf.get_variable("a", [2], initializer=tf.zeros_initializer())
    b = tf.get_variable("b", [2], initializer=tf.ones_initializer())
    
g2 = tf.Graph()
with g2.as_default():
    a = tf.get_variable("a", [2], initializer=tf.ones_initializer())
    b = tf.get_variable("b", [2], initializer=tf.zeros_initializer())
    
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print("g1 - a", sess.run(tf.get_variable("a")))
        print("g1 - b", sess.run(tf.get_variable("b")))
        
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        print("g2 - a", sess.run(tf.get_variable("a")))
        print("g2 - b", sess.run(tf.get_variable("b")))


# class Graph:
#     def __init__(self):
#         pass